### ISSUE TITLE
bad response 404 on Icinga 2.11

### ISSUE THREAD

**Issue by jameskaf** [sni/lmd#92] opened 2020-01-03 03:13 UTC
bad response: 404 31 error on lmd, fresh install. Tried thru Thruk and standalone lmd. Here is the trace info:

`
[2020-01-03 03:10:20.331][Info][listener.go:296] listening for incoming queries on unix /tmp/lmd.sock
[2020-01-03 03:10:20.332][Info][listener.go:365] listening for rest queries on :8080
[2020-01-03 03:10:20.332][Info][listener.go:296] listening for incoming queries on tcp 127.0.0.1:3333
[2020-01-03 03:10:20.332][Info][peer.go:251] [Prod] starting connection
[2020-01-03 03:10:20.332][Trace][peer.go:1632] [Prod] no cached connection found
[2020-01-03 03:10:20.332][Trace][peer.go:1322] [Prod] query: GET status
ResponseHeader: fixed16
OutputFormat: json
Columns: program_start accept_passive_host_checks accept_passive_service_checks cached_log_messages check_external_commands check_host_freshness check_service_freshness connections connections_rate enable_event_handlers enable_flap_detection enable_notifications execute_host_checks execute_service_checks forks forks_rate host_checks host_checks_rate interval_length last_command_check last_log_rotation livestatus_version log_messages log_messages_rate nagios_pid neb_callbacks neb_callbacks_rate obsess_over_hosts obsess_over_services process_performance_data program_version requests requests_rate service_checks service_checks_rate
KeepAlive: on

[2020-01-03 03:10:20.333][Trace][peer.go:1359] [Prod] result: [[1576361802.0,1.0,1.0,0.0,1.0,1.0,1.0,3208.0,0.0019334410862108127,1.0,1.0,1.0,1.0,1.0,0.0,0.0,43476.0,0.026202707189399623,60.0,0.0,0.0,"2.11.2-1",0.0,0.0,42381.0,0.0,0.0,0.0,0.0,1.0,"2.11.2-1",0.0,0.0,601108.0,0.36228394776641054]]
[2020-01-03 03:10:20.333][Debug][peer.go:1381] [Prod] fetched table:          status - time:       0s - count:        1 - size:        0 kB
[2020-01-03 03:10:20.333][Trace][peer.go:1632] [Prod] no cached connection found
[2020-01-03 03:10:20.334][Trace][peer.go:1322] [Prod] query: GET columns
ResponseHeader: fixed16
OutputFormat: json
Columns: table name
KeepAlive: on

[2020-01-03 03:10:20.334][Debug][peer.go:1475] [Prod] LastQuery:
[2020-01-03 03:10:20.334][Debug][peer.go:1476] [Prod] GET columns
ResponseHeader: fixed16
OutputFormat: json
Columns: table name
KeepAlive: on

[2020-01-03 03:10:20.334][Debug][peer.go:1342] [Prod] sending data/query failed: [Prod] bad response: 404          31
[2020-01-03 03:10:20.334][Trace][peer.go:1308] [Prod] put cached connection back
[2020-01-03 03:10:20.334][Debug][peer.go:1665] [Prod] connection error 192.168.0.101:6666: [Prod] bad response: 404          31
[2020-01-03 03:10:20.334][Debug][peer.go:1699] [Prod] last online: never
[2020-01-03 03:10:20.334][Info][peer.go:1702] [Prod] site went offline: [Prod] bad response: 404          31
[2020-01-03 03:10:25.334][Trace][peer.go:1632] [Prod] no cached connection found
[2020-01-03 03:10:25.335][Trace][peer.go:1322] [Prod] query: GET status
ResponseHeader: fixed16
OutputFormat: json
Columns: program_start accept_passive_host_checks accept_passive_service_checks cached_log_messages check_external_commands check_host_freshness check_service_freshness connections connections_rate enable_event_handlers enable_flap_detection enable_notifications execute_host_checks execute_service_checks forks forks_rate host_checks host_checks_rate interval_length last_command_check last_log_rotation livestatus_version log_messages log_messages_rate nagios_pid neb_callbacks neb_callbacks_rate obsess_over_hosts obsess_over_services process_performance_data program_version requests requests_rate service_checks service_checks_rate
KeepAlive: on

[2020-01-03 03:10:25.339][Trace][peer.go:1359] [Prod] result: [[1576361802.0,1.0,1.0,0.0,1.0,1.0,1.0,3212.0,0.0019358460202393028,1.0,1.0,1.0,1.0,1.0,0.0,0.0,43418.0,0.026167672013151556,60.0,0.0,0.0,"2.11.2-1",0.0,0.0,42381.0,0.0,0.0,0.0,0.0,1.0,"2.11.2-1",0.0,0.0,599096.0,0.3610702388930429]]
[2020-01-03 03:10:25.339][Debug][peer.go:1381] [Prod] fetched table:          status - time:       0s - count:        1 - size:        0 kB
[2020-01-03 03:10:25.339][Trace][peer.go:1632] [Prod] no cached connection found
`

Any ideas? Looks like it stopped working with 2.11, but not quite sure yet

Thanks!

**Comment by jameskaf** [comment] 2020-01-03 03:51
Thruk works fine with Icinga2 Livestatus, but LMD doesn't for some reason....

**Comment by sni** [comment] 2020-01-03 10:42
Seems like icinga2 does not have a `columns` table like the other livestatus implementations.

**Comment by sni** [comment] 2020-01-03 10:44
But this has been adressed in e098d115a1a5daa3fe7cb6a28b41f4040feeef30. Which version do you use?

**Comment by jameskaf** [comment] 2020-01-05 21:56
Hi Sven, thanks for your reply. I've compiled this from the latest sources, based on the documentation:

`
lmd - version 1.7.1 (Build: )
`

Thank you!

**Comment by sni** [comment] 2020-01-05 21:57
great

**Comment by jameskaf** [comment] 2020-01-05 21:58
But still unfortunately, it doesn't work...

**Comment by sni** [comment] 2020-01-05 21:59
still the same error?

**Comment by jameskaf** [comment] 2020-01-05 22:02
yes, Sir, still the same error. Logs:

`
[2020-01-05 22:01:17.093][Debug][peer.go:1342] [CES] sending data/query failed: [CES] bad response: 404          31
[2020-01-05 22:01:17.093][Trace][peer.go:1308] [CES] put cached connection back
[2020-01-05 22:01:17.093][Debug][peer.go:1665] [CES] connection error 10.8.235.159:6666: [CES] bad response: 404          31
[2020-01-05 22:01:17.093][Debug][peer.go:1699] [CES] last online: never
[2020-01-05 22:01:22.091][Trace][peer.go:1632] [CES] no cached connection found
[2020-01-05 22:01:22.091][Trace][peer.go:1322] [CES] query: GET status
ResponseHeader: fixed16
OutputFormat: json
Columns: program_start accept_passive_host_checks accept_passive_service_checks cached_log_messages check_external_commands check_host_freshness check_service_freshness connections connections_rate enable_event_handlers enable_flap_detection enable_notifications execute_host_checks execute_service_checks forks forks_rate host_checks host_checks_rate interval_length last_command_check last_log_rotation livestatus_version log_messages log_messages_rate nagios_pid neb_callbacks neb_callbacks_rate obsess_over_hosts obsess_over_services process_performance_data program_version requests requests_rate service_checks service_checks_rate
KeepAlive: on

[2020-01-05 22:01:22.092][Trace][peer.go:1359] [CES] result: [[1578214814.0,1.0,1.0,0.0,1.0,1.0,1.0,5640.0,0.12035812972766989,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1450.0,0.030943136183498518,60.0,0.0,0.0,"2.11.2-1",0.0,0.0,537.0,0.0,0.0,0.0,0.0,1.0,"2.11.2-1",0.0,0.0,18639.0,0.39775801051784015]]
[2020-01-05 22:01:22.092][Debug][peer.go:1381] [CES] fetched table:          status - time:       0s - count:        1 - size:        0 kB
[2020-01-05 22:01:22.092][Trace][peer.go:1632] [CES] no cached connection found
[2020-01-05 22:01:22.093][Trace][peer.go:1322] [CES] query: GET columns
ResponseHeader: fixed16
OutputFormat: json
Columns: table name
KeepAlive: on

[2020-01-05 22:01:22.094][Debug][peer.go:1475] [CES] LastQuery:
[2020-01-05 22:01:22.094][Debug][peer.go:1476] [CES] GET columns
ResponseHeader: fixed16
OutputFormat: json
Columns: table name
KeepAlive: on

[2020-01-05 22:01:22.094][Debug][peer.go:1342] [CES] sending data/query failed: [CES] bad response: 404          31
[2020-01-05 22:01:22.094][Trace][peer.go:1308] [CES] put cached connection back
[2020-01-05 22:01:22.094][Debug][peer.go:1665] [CES] connection error 10.0.0.1:6666: [CES] bad response: 404          31
[2020-01-05 22:01:22.094][Debug][peer.go:1699] [CES] last online: never
`

**Comment by jameskaf** [comment] 2020-01-05 22:04
Icinga2 version:

`
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)
`

icinga2 livestatus config:

`
library "livestatus"

object LivestatusListener "livestatus-tcp" {
  socket_type = "tcp"
  bind_host = "0.0.0.0"
  bind_port = "6666"
}
`

**Comment by sni** [comment] 2020-01-05 22:07
i will try to reproduce that in the next days.

**Comment by jameskaf** [comment] 2020-01-07 19:38
thank you Sven

**Comment by jameskaf** [comment] 2020-01-13 05:50
Do you need any help with debugging?

**Comment by sni** [comment] 2020-01-13 09:20
No, just haven't found a free timeslot yet.

**Comment by jameskaf** [comment] 2020-01-17 02:38
That's great fix @lpopil! Thanks much!

**Comment by sni** [comment] 2020-01-17 07:55
hmm, thats bad, because that regular expression is valid for almost everything else as well.

**Comment by druchoo** [comment] 2020-04-26 22:20
Thanks @lpopil! 

@sni submitted PR https://github.com/sni/lmd/pull/96 based on Icinga2 repo version search regex and suggestion from @lpopil.

[icinga2/lib/base/utility.cpp#L1184](https://github.com/Icinga/icinga2/blob/af7768944a3b95f2a6509f2fb87949044a09cf83/lib/base/utility.cpp#L1184)

```boost::regex pattern("^[vr]?(2\\.\\d+\\.\\d+).*$");```

Tested successfully with v2.10.x & v2.11.x.

**Comment by sni** [comment] 2020-04-27 07:36
It will work again (hopefully with Icinga 2.12 if the PR here https://github.com/Icinga/icinga2/pull/7931 got merged. LMD is already prepared and ready. There is nothing we can do here so far.

**Comment by sni** [comment] 2020-07-08 14:58
See #95  for a possible workaround.

**Closed** 2021-01-22 16:14 UTC
